#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#define REQUEST_ERR "Bad Request"
#define NOT_FOUND "Not Found"
#define PERMISSION_DENIED "Permission Denied"
#define EMPTY "Empty"
using namespace std;
class User
{
public:
    void set_new_user(const string& user_name, const string& password, const string& mode, const int&id)
    {
        this ->user_name = user_name;
        this ->set_password(password);
        this ->mode = mode;
        this ->user_id = id;
        this ->status = 1;        
    }
    string user_name;
    int user_id;
    string mode;
    int status = 0;
    string get_password() {return password;};
    void set_password(string password) {this -> password = password;};
    vector<string> print_user()
    {
        vector<string> res(4); // Initialize the vector with 4 elements
        res[0] = to_string(this->user_id); // Convert int to string
        res[1] = this->mode;
        res[2] = this->user_name;
        res[3] = to_string(this->song_num()); // Convert int to string
        return res;
    }
    virtual int song_num() = 0;
private:
    string password;
};

class RegularUsr : public User
{
public:
    int song_num() override
    {
        return playlist_num;
    }
private:
    int playlist_num = 0;
};

class Artist : public User
{
public:
    int song_num() override
    {
        return songs_num;
    }
private:
    int songs_num = 0;
};

class Song
{
public:
    void print_song()
    {
        cout << song_id << ", " << song_name << ", " << artist << endl;
    }
private:
    string song_name;
    string artist;
    int song_id;
    int Year;
    string Album;
    string Tags;
    int Duration;
};

class CommandManagement
{
public:

    string extract_content(const string& input) 
    {
        string result;
        bool inside_brackets = false;
        for (char c : input) 
        {
            if (c == '<') 
            {
                inside_brackets = true;
            } else if (c == '>') 
            {
                inside_brackets = false;
            } else if (inside_brackets)
            {
                result += c;
            }
        }
        return result;
        //generated by AI
    }
    void sign_up(const string& user_name, const string& password, const string& mode)
    {
        for(const auto& user : users)
        {
            if(user_name == user->user_name)
            {
                throw REQUEST_ERR;
            }
        }
        User* new_user;
        if(mode == "user")
        {
            new_user = new RegularUsr;
        }
        else if(mode == "artist")
        {
            new_user = new Artist;
        }
        else
        {
            throw REQUEST_ERR;
        }
        new_user->set_new_user(user_name, password, mode, next_user_id);
        next_user_id += 1;
        new_user->status = 1;
        users.push_back(new_user);
        current_user = new_user;
        throw string("OK");
    }

    void login(const string& user_name, const string& password)
    {
        int tmp = 0;
        for(const auto& user : users)
        {
            if(user->user_name == user_name)
            {
                tmp = 1;
                if(user->get_password() == password)
                {
                    tmp = 2;
                    user->status = 1;
                    current_user = user;
                    throw string("OK");
                }
            }
        }
        if(tmp == 0)
        {
            throw NOT_FOUND;
        }
        if(tmp == 1)
        {
            throw PERMISSION_DENIED;
        }
    }

    void log_out()
    {
        current_user = nullptr;
        throw string("OK");
    }

    void handle_read_input(const string& command)
    {
        tokens.clear();
        istringstream iss(command);
        string token = "";
        bool insideBlock = false;
        string blockValue = ""; 

        while (getline(iss, token, ' ')) 
        {
            if (token.front() == '<' && token.back() != '>')
            {
                insideBlock = true;
                blockValue = token.substr(1);
            }
            else if (insideBlock && token.back() == '>')
            {
                insideBlock = false;
                blockValue += " " + token.substr(0, token.size() - 1);
                tokens.push_back(blockValue);
            }
            else if (insideBlock)
            {
                blockValue += " " + token;
            }
            else
            {
                tokens.push_back(token);
            }
        }        
    }

    void handle_command_post_type(const string& order)
    {
        if(order == "signup")
        {
            if(current_user != nullptr)
            {
                throw PERMISSION_DENIED;
            }
            sign_up(tokens[4], extract_content(tokens[6]), extract_content(tokens[8]));
        }

        if(order == "login")
        {
            if(current_user != nullptr)
            {
                throw PERMISSION_DENIED;
            }
            login(tokens[4], extract_content(tokens[6]));
        }
        if(order == "logout")
        {
            if(current_user == nullptr)
            {
                throw PERMISSION_DENIED;
            }
            log_out();
        }
    }

    void handle_command_get_type(const string& order)
    {
        bool all = true;
        if(current_user == nullptr)
        {
            throw PERMISSION_DENIED;
        }
        if(tokens.size() > 3)
        {
            all = false;
            int id = stoi(tokens[4]);
        }
        if(order == "musics")
        {
            if(all == true)
            {
                for(int i = 0; i < songs.size(); i++)
                {
                    songs[i].print_song();
                }
            }
        }
        if(order == "users")
        {
            if(users.size() == 0)
                throw EMPTY;
            if(all == true)
            {
                
            }
            else
            {

            }
        }
    }

    void print_all_users()
    {
        for(int i = 0; i < users.size(); i++)
        {
            users[i]->print_user();
        }
    }
    void process_command()
    {
        int check = 0;
        if(tokens[0] == "POST")
        {
            for(const string& order : post_orders)
            {
                if(tokens[1] == order)
                {
                    check = 1;
                    handle_command_post_type(order);
                }
            }
            if(check == 0)
            {
                throw NOT_FOUND;
            }
        }

        else if(tokens[0] == "GET")
        {
            for(const string& order : get_orders)
            {
                if(tokens[1] == order)
                {
                    check = 1;
                    handle_command_get_type(order);
                }
            }
            if(check == 0)
            {
                throw NOT_FOUND;
            }        
        }

        else if(tokens[0] == "DELETE")
        {

        }

        else if(tokens[0] == "PUT")
        {

        }

        else
            throw REQUEST_ERR;
    }

    void print_users()
    {
        cout << "ID, Mode, Username, Playlists_number/Songs_number" << endl;
        for(int i = 0; i < users.size(); i++)
        {
            vector<string> user_info = users[i]->print_user(); // Get the user info vector
            for(int j = 0; j < 4; j++)
            {
                cout << user_info[j]; // Print each element of the user info vector
                cout << ", ";
            }
            cout << "\n";
        }
    }
    void print_all_songs()
    {
        cout << "ID, Name, Artist" << endl;
        for(auto& song : songs)
        {
            song.print_song();
        }
    }

    void set_orders()
    {
        post_orders.push_back("signup");
        post_orders.push_back("login");
        post_orders.push_back("logout");
        post_orders.push_back("playlist");
        post_orders.push_back("music");

        get_orders.push_back("musics");
        get_orders.push_back("users");

    }
    
    void run(const string& command)
    {
        handle_read_input(command);
        try
        {
            process_command();
        }
        catch(const string& EX_msg)
        {
            cout << ":normal af:" << endl;
            cout << EX_msg << endl;
        }
        catch(const char* ex)
        {
            cout << "wtf" << endl;
            cout << ex << endl;
        }
        catch(...)
        {
            cout << "An unexpected error occurred." << endl;
        }
        for(int i = 0; i < users.size(); i++)
        {
            cout << users[i]->user_name << " " << users[i]->get_password() << " " << users[i]->user_id << " " << users[i]->mode << endl;
            cout << "----------------------" << endl;
        }
    }
private:
    string command_type;
    int song_id;
    vector<User*> users;
    int next_user_id = 1;
    User* current_user = nullptr;
    vector<string> post_orders;
    vector<string> get_orders;
    vector<string> delete_orders;
    vector<string> put_ordres;
    vector<Song> songs;
    vector<string> tokens;
};
 
int main(int argc, char* argv[])
{
    string command;
    CommandManagement command_management;
    command_management.set_orders();
    while(true)
    {
        getline(cin, command);
        command_management.run(command);
        if(command.empty())
        {
            return 0;
        }
    }
}
